name: restaurant_ratings
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hooks_riverpod: ^2.4.10
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path_provider: ^2.1.2
  riverpod: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/restaurants.json
